name: 'snowflake_utils'
version: '0.0.1'

profile: default

require-dbt-version: ">=0.15.0"

source-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
test-paths: ["test"]
macro-paths: ["macros"]
log-path: "logs"

models:
  snowflake:
    audit:
      materialized: incremental
      optional:
        enabled: false
      vars:
        'snowflake:minutes_per_batch' : 30 
        ## Time period to request at once. If over 10,000 queries were run in the time period, Snowflake will return the last 10,000. #}
        'snowflake:max_load_minutes': 4320
        ## the number of minutes in 3 days - the maximum time to run for.